//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace seyahatbiletcim1.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("seyahatbiletcim1.Resource.HomeText", typeof(HomeText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        public static string ABOUTUS {
            get {
                return ResourceManager.GetString("ABOUTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVITIES.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url address.
        /// </summary>
        public static string adress {
            get {
                return ResourceManager.GetString("adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRPLANE.
        /// </summary>
        public static string Airplane {
            get {
                return ResourceManager.GetString("Airplane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Price.
        /// </summary>
        public static string BiletFiyati {
            get {
                return ResourceManager.GetString("BiletFiyati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Ticket.
        /// </summary>
        public static string BiletSatinAl {
            get {
                return ResourceManager.GetString("BiletSatinAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS.
        /// </summary>
        public static string Bus {
            get {
                return ResourceManager.GetString("Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT US.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string dahafazlasi {
            get {
                return ResourceManager.GetString("dahafazlasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string detay {
            get {
                return ResourceManager.GetString("detay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival History.
        /// </summary>
        public static string donustarih {
            get {
                return ResourceManager.GetString("donustarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVITIES.
        /// </summary>
        public static string etkinlik {
            get {
                return ResourceManager.GetString("etkinlik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participate in Participatory Events with Travelbiletcim.com!.
        /// </summary>
        public static string etkinlikslider {
            get {
                return ResourceManager.GetString("etkinlikslider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Price Range.
        /// </summary>
        public static string GecelikF {
            get {
                return ResourceManager.GetString("GecelikF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going History.
        /// </summary>
        public static string gidistarih {
            get {
                return ResourceManager.GetString("gidistarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string güncelle {
            get {
                return ResourceManager.GetString("güncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7/24 HELP.
        /// </summary>
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7/24 After Sales Support If you want to cancel or change the ticket you purchased, call our support team which is available 24 hours a day, 7 days a week!.
        /// </summary>
        public static string HELP724 {
            get {
                return ResourceManager.GetString("HELP724", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOTEL.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string iade {
            get {
                return ResourceManager.GetString("iade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to the fact that the fastest and easiest way to travel is to fly; immediately call the cheapest airline tickets, make the most suitable ticket for the price and buy it online!.
        /// </summary>
        public static string icerik1 {
            get {
                return ResourceManager.GetString("icerik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Ticket.
        /// </summary>
        public static string icerik11 {
            get {
                return ResourceManager.GetString("icerik11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Ticket.
        /// </summary>
        public static string icerik2 {
            get {
                return ResourceManager.GetString("icerik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you think bus travel is the best option to go from one city to another, call the cheapest bus tickets and buy your ticket online!.
        /// </summary>
        public static string icerik22 {
            get {
                return ResourceManager.GetString("icerik22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7/24 SUPPORT.
        /// </summary>
        public static string icerik3 {
            get {
                return ResourceManager.GetString("icerik3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can reach my 24/7 ticketing agent. Metro Tourism customer service. You can reach Ertürk Lines customer service..
        /// </summary>
        public static string icerik33 {
            get {
                return ResourceManager.GetString("icerik33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVITIES.
        /// </summary>
        public static string icerik4 {
            get {
                return ResourceManager.GetString("icerik4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Trip Trips at affordable prices! Follow university trips! Choose your best Work And Travel company from us! Investigate the InterRail groups from us!.
        /// </summary>
        public static string icerik44 {
            get {
                return ResourceManager.GetString("icerik44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakarya University Department of Computer Engineering.
        /// </summary>
        public static string iletisim {
            get {
                return ResourceManager.GetString("iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University of Sakarya.
        /// </summary>
        public static string iletisim1 {
            get {
                return ResourceManager.GetString("iletisim1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEYAHATBİLETCİM CONTACTS.
        /// </summary>
        public static string iletisim2 {
            get {
                return ResourceManager.GetString("iletisim2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT FORM.
        /// </summary>
        public static string iletisim3 {
            get {
                return ResourceManager.GetString("iletisim3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string iletisim4 {
            get {
                return ResourceManager.GetString("iletisim4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERRAIL TURKEY.
        /// </summary>
        public static string INTERRAILTURKEY {
            get {
                return ResourceManager.GetString("INTERRAILTURKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string kayit {
            get {
                return ResourceManager.GetString("kayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Kayit1 {
            get {
                return ResourceManager.GetString("Kayit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Kayit2 {
            get {
                return ResourceManager.GetString("Kayit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Kayit3 {
            get {
                return ResourceManager.GetString("Kayit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Repeat.
        /// </summary>
        public static string Kayit4 {
            get {
                return ResourceManager.GetString("Kayit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seyahatbiletcim New Membership Page.
        /// </summary>
        public static string Kayit5 {
            get {
                return ResourceManager.GetString("Kayit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us at Seyahatbiletcim.com!.
        /// </summary>
        public static string Kayit6 {
            get {
                return ResourceManager.GetString("Kayit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        public static string Konaklama {
            get {
                return ResourceManager.GetString("Konaklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOMMODATION LIST.
        /// </summary>
        public static string KONAKLAMAlist {
            get {
                return ResourceManager.GetString("KONAKLAMAlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Konuk {
            get {
                return ResourceManager.GetString("Konuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seyahatbiletcim Login Page.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Seyahatbiletcim.com!.
        /// </summary>
        public static string login1 {
            get {
                return ResourceManager.GetString("login1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string login2 {
            get {
                return ResourceManager.GetString("login2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string login3 {
            get {
                return ResourceManager.GetString("login3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        public static string Nerede {
            get {
                return ResourceManager.GetString("Nerede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where from.
        /// </summary>
        public static string nereden {
            get {
                return ResourceManager.GetString("nereden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to.
        /// </summary>
        public static string nereye {
            get {
                return ResourceManager.GetString("nereye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOTEL SEARCH.
        /// </summary>
        public static string OTELARAMA {
            get {
                return ResourceManager.GetString("OTELARAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your place to stay with Travelbiletcim.com!.
        /// </summary>
        public static string otelslider {
            get {
                return ResourceManager.GetString("otelslider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The detailed information of Lux Houses is available with the search conditions you want..
        /// </summary>
        public static string otelslider1 {
            get {
                return ResourceManager.GetString("otelslider1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Search.
        /// </summary>
        public static string otelslider2 {
            get {
                return ResourceManager.GetString("otelslider2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS SEARCH.
        /// </summary>
        public static string OTOBUSARAMA {
            get {
                return ResourceManager.GetString("OTOBUSARAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Tickets.
        /// </summary>
        public static string OtobusBilet {
            get {
                return ResourceManager.GetString("OtobusBilet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Otobusfirma {
            get {
                return ResourceManager.GetString("Otobusfirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS RANGE.
        /// </summary>
        public static string OTOBUSSEFER {
            get {
                return ResourceManager.GetString("OTOBUSSEFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey&apos;s Most Visitor Bus Ticket Site!.
        /// </summary>
        public static string otobusslider {
            get {
                return ResourceManager.GetString("otobusslider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Payment, Canceled Bilete Continuous Return, More than 4 Million Visitors per Month, No Commission, Free.
        /// </summary>
        public static string otobusslider1 {
            get {
                return ResourceManager.GetString("otobusslider1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Ticket.
        /// </summary>
        public static string otobusslider2 {
            get {
                return ResourceManager.GetString("otobusslider2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR SPONSORS.
        /// </summary>
        public static string OURSPONSORS {
            get {
                return ResourceManager.GetString("OURSPONSORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the hotel you are looking for with Seyahatbiletcim.com now!.
        /// </summary>
        public static string reklamotel {
            get {
                return ResourceManager.GetString("reklamotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SING IN.
        /// </summary>
        public static string Signin {
            get {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SING UP.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Sinif {
            get {
                return ResourceManager.GetString("Sinif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Tarih {
            get {
                return ResourceManager.GetString("Tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Type.
        /// </summary>
        public static string TesisTipi {
            get {
                return ResourceManager.GetString("TesisTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRPLANE SEARCH.
        /// </summary>
        public static string UCAKARAMA {
            get {
                return ResourceManager.GetString("UCAKARAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air tickets.
        /// </summary>
        public static string UcakBilet {
            get {
                return ResourceManager.GetString("UcakBilet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string UcakFirmaAdi {
            get {
                return ResourceManager.GetString("UcakFirmaAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRPLANE RANGE.
        /// </summary>
        public static string ucaksefer {
            get {
                return ResourceManager.GetString("ucaksefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheap Air Ticket Prices at Travelbiletcim.com!.
        /// </summary>
        public static string ucakslider {
            get {
                return ResourceManager.GetString("ucakslider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7/24 Customer Service, Secure Payment, Get 2 Minute Ticket.
        /// </summary>
        public static string ucakslider1 {
            get {
                return ResourceManager.GetString("ucakslider1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Ticket.
        /// </summary>
        public static string ucakslider2 {
            get {
                return ResourceManager.GetString("ucakslider2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIVERSITY TRAVEL.
        /// </summary>
        public static string UNIVERSITYTRAVEL {
            get {
                return ResourceManager.GetString("UNIVERSITYTRAVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be a member of our site to benefit from our tickets.
        /// </summary>
        public static string uyeistek {
            get {
                return ResourceManager.GetString("uyeistek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORK AND TRAVEL.
        /// </summary>
        public static string WORKANDTRAVE {
            get {
                return ResourceManager.GetString("WORKANDTRAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Stars.
        /// </summary>
        public static string YildizSayisi {
            get {
                return ResourceManager.GetString("YildizSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger Capacity.
        /// </summary>
        public static string Yolcu {
            get {
                return ResourceManager.GetString("Yolcu", resourceCulture);
            }
        }
    }
}
